name: Node Docker image

on: [pull_request]
# on:
#   push:
#     branches:
#       - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build Walchain node image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: walchain/walchain-node:latest

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: walchain
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image_name: walchain/walchain-node
          image_tag: latest
          push_git_tag: true
